mutation {
  exportOracleDatabase(input: {
    request: {
      id: "40bac7c1-87ad-4ac0-b4a6-34ac592d8e77"
      config: {
        # Set exactly ONE of timestampMs, snapshotId, or scn
        recoveryPoint: {
          timestampMs: 1737000000000   # epoch milliseconds (Jan 2025)
        }
        # OracleHost FID for standalone DBs, OracleRac FID for RAC DBs
        targetOracleHostOrRacId: "11111111-2222-3333-4444-555555555555"
        numChannels: 2
      }
    }
  }) {
    id
    status
  }
}
