query {
  customTprPolicies {
    nodes {
      policyId
      policyName
      description
      orgName
      quorumRequirement
      actions
      numberOfObjectTypes
      numberOfProtectableObjects
    }
  }
}
