query {
  cloudDirectNasShare(fid: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11") {
    id
    name
    protocol
    ncdPolicyName
    cloudDirectId
    isRelic
    isStale
    totalSnapshots
    newestSnapshot {
      id
      date
    }
    oldestSnapshot {
      id
      date
    }
    effectiveSlaDomain {
      id
      name
    }
    cloudDirectNasSystem {
      id
      name
      vendorType
    }
    cloudDirectNasNamespace {
      id
      name
    }
  }
}
