query {
  searchSnappableVersionedFiles(
    snappableFid: "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11"
    searchQuery: "quarterly-report"
    usePrefixSearch: false
  ) {
    nodes {
      absolutePath
      displayPath
      filename
      fileVersions {
        snapshotId
        size
        lastModified
        fileMode
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
