site_name: Rubrik Developer Guide
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.superfences
