site_name: Rubrik Developer Guide
theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/arrow-right-circle
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
#    - navigation.sections
extra_css:
  - css/extra.css
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: Site usage statistics (Mixpanel)
  generator: false  
  analytics:
    provider: mixpanel
    # Project token here is NOT a secret. It's used to identify the project in Mixpanel and is write only
    project_token: 9949d865e3afe70668e198cc55b31299
  static_templates:
    - 404.html
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
      base_path: .
      auto_append:
        - includes/glossary.md
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: iso_date
watch:
  - includes
  - code
  - overrides
