site_name: Rubrik Developer Guide
theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    annotation: material/arrow-right-circle
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - navigation.tabs
    - navigation.indexes
#    - navigation.sections
extra_css:
     - css/extra.css
extra: 
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false
  analytics:
    provider: google
    property: G-JTRX271SWK
    feedback:
      title: Did you find what you needed?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Yes I did!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: No, I didn't.
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve our content by
            using our <a href="https://docs.google.com/forms/d/e/1FAIpQLSe-U-S214aDsilkileoKhtJ100hLdN3RTk2-jrypFMwpmg_nQ/viewform?usp=pp_url&entry.478726986={title}+-+{url}" target="_blank" rel="noopener">feedback form</a>.
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: .
      auto_append:
        - includes/glossary.md
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: iso_date  
watch:
  - includes
  - snippets
  - scripts