query {
  nasShares(filter: [
    {field: NAME_EXACT_MATCH texts: "example"}
    {field: IS_RELIC texts: "false"}
    {field: IS_REPLICATED texts: "false"}
  ]) {
    nodes {
      name
      id
      cdmId
      shareType
      exportPoint
      isChangelistEnabled
      isStale
      nasSystem {
        name
        id
      }
      nasVolume {
        name
        id
        nasNamespace {
          name
          id
        }
      }
      primaryFileset {
        name
        id
      }
      connectedThrough
      hostAddress
      hostIdForRestore
      cluster {
        name
        id
      }
      effectiveSlaDomain {
        name
        id
      }
    }
  }
}