query {
  saasAppOrganizations(
    typeFilter: [SALESFORCE_ORGANIZATION]
    first: 50
  ) {
    count
    nodes {
      id
      name
      status
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
