// Client-side search over docs/javascripts/../Rubrik-Security-Cloud-API/API-Reference/search-index.json.
// The index is generated by tools/generate_api_reference.py and lists every
// query, mutation, and type — the ~10k reference pages excluded from the
// built-in Material search (see exclude-search in mkdocs.yml) because there
// are too many of them for that index to stay fast.
(function () {
  const KIND_LABELS = {
    query: "Query",
    mutation: "Mutation",
    object: "Object",
    input: "Input",
    enum: "Enum",
    interface: "Interface",
    union: "Union",
    scalar: "Scalar",
  };

  document.addEventListener("DOMContentLoaded", () => {
    const input = document.getElementById("schema-search-input");
    const results = document.getElementById("schema-search-results");
    const status = document.getElementById("schema-search-status");
    const filters = document.getElementById("schema-search-filters");
    if (!input || !results) return;

    const filterBoxes = filters
      ? Array.from(filters.querySelectorAll('input[type="checkbox"]'))
      : [];

    function selectedKinds() {
      if (filterBoxes.length === 0) return null; // no filter UI: allow everything
      return new Set(filterBoxes.filter((cb) => cb.checked).map((cb) => cb.value));
    }

    let index = null;
    let indexPromise = null;

    function loadIndex() {
      if (indexPromise) return indexPromise;
      status.textContent = "Loading index...";
      indexPromise = fetch("search-index.json")
        .then((r) => {
          if (!r.ok) throw new Error(`HTTP ${r.status}`);
          return r.json();
        })
        .then((data) => {
          index = data;
          status.textContent = "";
        })
        .catch((err) => {
          status.textContent = "Could not load search index.";
          console.error("schema-search: failed to load search-index.json", err);
        });
      return indexPromise;
    }

    // Scored substring match: name match ranks above description match,
    // and an earlier / exact match ranks above a later one.
    function score(entry, q) {
      const name = entry.n.toLowerCase();
      if (name === q) return 100;
      if (name.startsWith(q)) return 90 - Math.min(name.length - q.length, 20);
      const nameIdx = name.indexOf(q);
      if (nameIdx !== -1) return 70 - nameIdx;
      const descIdx = (entry.d || "").toLowerCase().indexOf(q);
      if (descIdx !== -1) return 30 - Math.min(descIdx, 20);
      return -1;
    }

    function render(matches, q) {
      results.innerHTML = "";
      if (!q) {
        status.textContent = "";
        return;
      }
      if (matches.length === 0) {
        status.textContent = `No matches for "${q}".`;
        return;
      }
      status.textContent = `${matches.length} match${matches.length === 1 ? "" : "es"}${matches.length > 30 ? " (showing top 30)" : ""}`;
      const frag = document.createDocumentFragment();
      matches.slice(0, 30).forEach((entry) => {
        const row = document.createElement("a");
        row.className = "schema-search-result";
        row.href = entry.u;
        const kind = document.createElement("span");
        kind.className = `schema-search-kind schema-search-kind--${entry.k}`;
        kind.textContent = KIND_LABELS[entry.k] || entry.k;
        const name = document.createElement("code");
        name.className = "schema-search-name";
        name.textContent = entry.n;
        row.appendChild(kind);
        row.appendChild(name);
        if (entry.d) {
          const desc = document.createElement("span");
          desc.className = "schema-search-desc";
          desc.textContent = entry.d;
          row.appendChild(desc);
        }
        frag.appendChild(row);
      });
      results.appendChild(frag);
    }

    function runSearch() {
      const q = input.value.trim().toLowerCase();
      if (!q) {
        render([], "");
        return;
      }
      if (!index) return;
      const kinds = selectedKinds();
      const matches = index
        .filter((entry) => !kinds || kinds.has(entry.k))
        .map((entry) => ({ entry, s: score(entry, q) }))
        .filter((m) => m.s >= 0)
        .sort((a, b) => b.s - a.s)
        .map((m) => m.entry);
      render(matches, q);
    }

    let debounceTimer = null;
    input.addEventListener("input", () => {
      clearTimeout(debounceTimer);
      debounceTimer = setTimeout(() => {
        loadIndex().then(runSearch);
      }, 100);
    });

    input.addEventListener("focus", () => loadIndex(), { once: true });

    filterBoxes.forEach((cb) => cb.addEventListener("change", runSearch));
  });
})();
