mutation LinkAvailabilityGroups {
  manageProtectionForLinkedObjects(input: {
    operation: LINK
    assignSlaReq: {
      objectIds: [
        "7734f7a2-9388-59e3-bcc5-25cb0a531910"
        "38fb7ce0-e616-53aa-a155-3b1c7216d44a"
      ]
      slaDomainAssignType: NO_ASSIGNMENT
    }
  }) {
    jobId
    taskchainId
  }
}
