mutation {
  bulkCreateFilesets(input: {
    clusterUuid: "8417a938-96f5-43c6-9905-b36e051c5f98"
    definitions: [
      {
        templateId: "11111111-2222-3333-4444-555555555555"
        hostId: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
      }
    ]
  }) {
    data {
      filesetSummary {
        id
        name
        hostId
      }
    }
  }
}
