mutation filesetExportSnapshotFiles {
  filesetExportSnapshotFiles(input: {
    # id is the snapshot ID.
    id: "f79b1102-77b5-4434-8400-c2a66c9b2dc1"
    osType: LINUX
    shareType: NoShareType
    config: {
      # Target physical host to export to. For a NAS share target,
      # set shareId instead of hostId.
      hostId: "a1b2c3d4-1111-2222-3333-444455556666"
      ignoreErrors: false
      exportPathPairs: [
        {
          exportPathPair: {
            srcPath: "/var/www/html/config.php"
            dstPath: "/restore/config.php"
          }
        }
      ]
    }
  }) {
    id
  }
}
