mutation db2OnDemandBackup {
  createOnDemandDb2Backup(input: {
    id: "c7bd8eb2-7132-4c8f-8592-682d507520dc"
    config: {
      slaId: "f79b1102-77b5-4434-8400-c2a66c9b2dc1"
      }
    }) {
      id
  }
}
