query getVirtualMachines {
  objects: vSphereVmNewConnection(
    filter: [
      {field: NAME_EXACT_MATCH texts: "foo"}
      {field: IS_RELIC texts: "false"}
      {field: IS_REPLICATED texts: "false"}
    ]
  ) {
    nodes {
      name
      id
    }
  }
}