query {
  snappableOnedriveSearch(
    orgId: "0876804E-1CB1-4F28-BCB3-B4390C15FA1F" # example UUID
    snappableFid: "123e4567-e89b-12d3-a456-426614174000"
  	onedriveSearchFilter: {
      searchKeywordFilter: {
      	keywordType: NAME
		searchKeyword: "example.pdf"
		# Replace the above with below for searching for file types
        #keywordType: FILE_TYPE
        #searchKeyword: "pdf"
      }
      searchObjectFilter: {
        # to search folders use O365_FOLDER
        searchObjectType: ONEDRIVE_FILE 
      }
    }
  ) {
    nodes {
      name
      id
      size
      parentFolderId
      channelName
      createTime
      modifiedTime
      ... on O365OnedriveFile {
        fileType
        objectType
        snapshotId
        snapshotNum
        snapshotTime
      }
      ... on O365OnedriveFolder {
        objectType
        snapshotId
        snapshotNum
        snapshotTime
      }
    }
  }
}