query {
  awsNativeEc2Instances(ec2InstanceFilters: {
    #nameOrIdSubstringFilter: {nameOrIdSubstring: "example"}
    #regionFilter: {regions: [US_EAST_1]}
    #tagFilter: {tagFilterParams: {tagKey: "foo" tagValue: "bar" filterType: TAG_KEY_VALUE}}
    #vpcFilter: {vpcIds: ["093e5470-22b4-483c-8910-fff0cbb982b1"]}
  }) {
    nodes {
      name
      id
      nativeName
      cloudNativeId
      instanceType
      region
      availabilityZone
      vpcName
      vpcId
      tags {
        key
        value
      }
      osType
      publicIp
      privateIp
      awsAccountRubrikId
      isAppConsistencyEnabled
      awsAccount {
        name
        id
      }
      attachedEbsVolumes {
        volumeName
        volumeNativeId
        cloudNativeId
        volumeType
        sizeInGiBs
      }
      effectiveSlaDomain {
        name
        id
      }
    }
  }
}