query {
  rcvAccountEntitlement {
    entitlements {
      usedCapacity
      expectedUsedCapacity
      entitlement {
        tier
        capacity
        redundancy
        expirationDate
      }
    }
  }
}
