query {
  rcvAccountEntitlement {
    backupEntitlement {
      capacity
      bundle
      tier
      redundancy
      createdAt
      revenueType
    }
    archiveEntitlement {
      capacity
      bundle
      tier
      redundancy
      createdAt
      revenueType
    }
    entitlements {
      entitlement {
        capacity
        bundle
        tier
        redundancy
        createdAt
        revenueType
      }
      usedCapacity
    }
  }
}