mutation {
  createServiceAccount(
    input: {
      name: "example"
      description: "example service account"
      roleIds: ["123e4567-e89b-12d3-a456-426614174000"]}
  ) {
    clientId
    clientSecret
    accessTokenUri
  }
}