query {
    serviceAccounts {
        nodes {
            name
            description
            clientId
            integrationName
            integrationId
            lastLogin
            roles {
                name
                id
            }
        }
    }
}