mutation {
  exportNutanixSnapshot(input: {
    id: "f5bc5502-b9a6-4759-bf02-05dc5a48f9f7"
    config: {
      containerNaturalId: "0005a1b2-1234-5678-90ab-cdef01234567"
      nutanixClusterId: "6450b2bb-3114-45ab-a45e-049c7f27b58e"
      vmName: "example-restored"
      powerOn: true
    }
  }) {
    id
    status
    progress
    error {
      message
    }
  }
}
